# Generated by Django 5.2.4 on 2025-08-24 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("post", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="postmassil",
            old_name="user",
            new_name="customer",
        ),
    ]
