# Generated by Django 5.2.4 on 2025-08-16 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Routine',
            fields=[
                ('routine_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.customer')),
            ],
        ),
        migrations.CreateModel(
            name='VisitRoutine',
            fields=[
                ('VisitRoutine_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_index', models.IntegerField(blank=True, null=True)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('routine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visit_points', to='route.routine')),
            ],
        ),
    ]
