# Generated by Django 5.2.4 on 2025-08-25 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=100)),
                ('reward', models.PositiveIntegerField(default=0)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customer')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.store')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerDailyMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assign_date', models.DateField()),
                ('status', models.CharField(choices=[('ASSIGNED', '배정됨'), ('COMPLETED', '완료'), ('INVALIDATED', '무효(다른 미션 완료됨)'), ('EXPIRED', '만료(다음날)')], default='ASSIGNED', max_length=16)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_missions', to='customer.customer')),
                ('owner_mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_entries', to='missions.ownermission')),
            ],
            options={
                'indexes': [models.Index(fields=['customer', 'assign_date'], name='missions_cu_custome_e51a0f_idx')],
                'unique_together': {('customer', 'assign_date', 'owner_mission')},
            },
        ),
    ]
