# Generated by Django 5.2.4 on 2025-08-11 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_created_at_customer_updated_at'),
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownermission',
            old_name='store_id',
            new_name='store',
        ),
        migrations.AddField(
            model_name='ownermission',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customer'),
        ),
        migrations.AddField(
            model_name='servicemission',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customer.customer'),
        ),
    ]
