# Generated by Django 5.2.4 on 2025-08-06 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("customer_id", models.AutoField(primary_key=True, serialize=False)),
                ("nickname", models.CharField(max_length=50)),
                ("intro", models.TextField(blank=True, null=True)),
                ("reward", models.IntegerField(default=0)),
            ],
        ),
    ]
