# Generated by Django 5.2.4 on 2025-08-25 12:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("category", "0001_initial"),
        ("customer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                ("store_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("open_date", models.DateField(null=True)),
                ("intro", models.TextField(blank=True, null=True)),
                ("address", models.CharField(default=" ", max_length=300)),
                (
                    "category",
                    models.ForeignKey(
                        db_column="Category_id",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="category.category",
                    ),
                ),
                (
                    "character",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stores",
                        to="customer.character",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Analysis",
            fields=[
                ("analysis_id", models.AutoField(primary_key=True, serialize=False)),
                ("data", models.URLField()),
                (
                    "store",
                    models.ForeignKey(
                        db_column="store_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="store.store",
                    ),
                ),
            ],
        ),
    ]
