# Generated by Django 5.2.4 on 2025-08-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Flyer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prompt", models.TextField()),
                ("negative_prompt", models.TextField(blank=True, default="")),
                ("width", models.PositiveIntegerField(default=768)),
                ("height", models.PositiveIntegerField(default=1024)),
                ("steps", models.PositiveIntegerField(default=30)),
                ("guidance_scale", models.FloatField(default=7.5)),
                ("seed", models.BigIntegerField()),
                ("image", models.ImageField(upload_to="flyers/%Y/%m/%d/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
